name: CI Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Build Tools
      shell: bash
      env:
          CC: /usr/bin/gcc-8
          CXX: /usr/bin/g++-8
      run: |
        mkdir build
        cd build
        cmake ..
        make -j
    - name: Tests
      shell: bash
      run: |
          cd build
          make test
    - uses: actions/upload-artifact@v1
      with:
        name: detector
        path: build/tools/detector
